name: Testing

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build --config Debug

      - name: Test
        run: |
          cd build
          ctest -C Debug --output-on-failure --verbose --output-junit test_results.xml

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYY-MM-DD-HH-mm

      - name: Save test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ github.run_number }}-${{ steps.current-time.outputs.formattedTime }}
          path: build/test_results.xml
          retention-days: 30

      # - name: Setup python
      #   uses: actions/setup-python@v2
      #   if: contains(matrix.os, 'ubuntu')
      #   with:
      #     python-version: 3.8

      # - name: Upload code coverage to coveralls
      #   if: contains(matrix.os, 'ubuntu')
      #   env:
      #     COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      #   run: |
      #     python -m venv venv
      #     source venv/bin/activate
      #     pip install --upgrade pip setuptools cpp-coveralls
      #     coveralls -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" --exclude "venv" --exclude "build/_deps"
